### ISSUE TITLE
Pinout image is wrong

### ISSUE THREAD

**Issue by aviogit** [Dot-and-Net/IoTHelpers#2]
Searching for "raspberry pi 3 pinout" on Google Images returns this page in the first row, but the image is wrong. Pin 8 and 10 are marked as "reserved" but in reality they're UART0 TX and RX. This may lead to errors if people don't double-check on other websites.

https://github.com/DotNetToscana/IoTHelpers/wiki/Raspberry-Pi-2-and-3-Pinout

**Comment by marcominerva** [comment]
Thank you for pointing that out, I have updated the image.

**Comment by aviogit** [comment]
Grande! :)
